spring.application.name=schemaspeak

gemini.api.key=${GEMINI_API_KEY}

spring.datasource.url=jdbc:mysql://database-1.cb6sg4mc2ogn.ap-southeast-2.rds.amazonaws.com:3306/schemaspeak?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=${RDS_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=5000